// ## This line will be ignored as it ends with "##"                          ##
// ## This line will be also ignored as it also ends with "##"                ##
// @Java: { nawa }

/** This is an exmaple code */

// Import area
import java.io.*;
import java.util.*;
import net.nawaman.script.*;

// Here is a local elements
static  int I = 0;
private int Factorial(int I) {
	return (I <= 1) ? 1 : I * Factorial(I - 1);
}

// Here is the Annotation
@SuppressWarnings("unchecked");

System.out.println("Hello World!!!");
System.out.println("Main Args = " + Arrays.toString($Args));	// Access Args
System.out.println("I = " + I);
System.out.println("Working Dir: " + (new File(".")).getAbsolutePath());

System.out.println("Factorial using local method");
for(int i = 0; i < 10; i++)
	System.out.println(i+"! = " + Factorial(i));

Function Fact = (Function)ScriptManager.Use("factorial");

System.out.println();
System.out.println("Factorial using ./ss_libs/factorial.ss via ScriptManager.Use(...)");
if(Fact != null) {
	for(int i = 0; i < 10; i++)
		System.out.println(i+"! = " + Fact.run(i));
}

System.out.println("DONE!!!");

return;



/*******************************************************************************
##:COMPILED::BASE64 {
rO0ABXcmACJuZXQubmF3YW1hbi5zY3JpcHQuamF2YS5KYXZhRW5naW5lAAB1cgACW0Ks8xf4BghU
4AIAAHhwAAAQcqztAAV3GQAKSkNPLU5FRURFRAADSkNPAAAAZAAAAAF1cgACW0Ks8xf4BghU4AIA
AHhwAAANk6ztAAVzcgAibmV0Lm5hd2FtYW4uamF2YWNvbXBpbGVyLkNsYXNzRGF0YVFeHaOMW6kD
AgAGWwAFQnl0ZXN0AAJbQkwABENvZGV0ABJMamF2YS9sYW5nL1N0cmluZztbAA9FbmNsb3NlZENs
YXNzZXN0ACVbTG5ldC9uYXdhbWFuL2phdmFjb21waWxlci9DbGFzc0RhdGE7TAAORW5jbG9zaW5n
Q2xhc3N0ACRMbmV0L25hd2FtYW4vamF2YWNvbXBpbGVyL0NsYXNzRGF0YTtMAAROYW1lcQB+AAJM
AARQYXRocQB+AAJ4cHVyAAJbQqzzF/gGCFTgAgAAeHAAAAx0yv66vgAAADIAmwoAJQBOCQAqAE8J
ACoAUAgAUQkAUgBTCgAqAFQKAFIAVQoAUgBWCgAqAFcKACoAWAoAKgBZBwBaCQBbAFwIAF0KAF4A
XwcAYAoAEABOCABhCgAQAGIKAGMAZAoAEABlCABmCQAqAGcKABAAaAgAaQcAaggAawoAGgBsCgAa
AG0IAG4IAG8IAHAKAFIAcQcAcgoAXgBzCAB0BwB1CgB2AHcLACIAeAoAEAB5CAB6BwB7BwB8BwB+
AQAFJENvZGUBABJMamF2YS9sYW5nL1N0cmluZzsBAAokU2lnbmF0dXJlAQAeTG5ldC9uYXdhbWFu
L3NjcmlwdC9TaWduYXR1cmU7AQABSQEABjxpbml0PgEATShMbmV0L25hd2FtYW4vc2NyaXB0L1Np
Z25hdHVyZTtMamF2YS9sYW5nL1N0cmluZztMbmV0L25hd2FtYW4vc2NyaXB0L1Njb3BlOylWAQAE
Q29kZQEAD0xpbmVOdW1iZXJUYWJsZQEADWdldEVuZ2luZU5hbWUBABQoKUxqYXZhL2xhbmcvU3Ry
aW5nOwEACWdldEVuZ2luZQEAIygpTG5ldC9uYXdhbWFuL3NjcmlwdC9TY3JpcHRFbmdpbmU7AQAH
Z2V0Q29kZQEADGdldFNpZ25hdHVyZQEAICgpTG5ldC9uYXdhbWFuL3NjcmlwdC9TaWduYXR1cmU7
AQAJRmFjdG9yaWFsAQAEKEkpSQEADVN0YWNrTWFwVGFibGUBAAUkU2VsZgEAFihbTGphdmEvbGFu
Zy9PYmplY3Q7KVYBAANydW4HAH8BAAZTaW1wbGUBAAxJbm5lckNsYXNzZXMBAEkoTG5ldC9uYXdh
bWFuL3NjcmlwdC9GdW5jdGlvbiRTaW1wbGU7W0xqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5n
L1ZvaWQ7AQA7KElMbmV0L25hd2FtYW4vc2NyaXB0L0Z1bmN0aW9uJFNpbXBsZTtbTGphdmEvbGFu
Zy9PYmplY3Q7KVYHAHIBAEsoTG5ldC9uYXdhbWFuL3NjcmlwdC9GdW5jdGlvbiRTaW1wbGU7W0xq
YXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBAAg8Y2xpbml0PgEAAygpVgEAClNv
dXJjZUZpbGUBADhuZXQubmF3YW1hbi5qYXZhY29tcGlsZXIuSmF2YUNvZGVNZW1vcnlGaWxlT2Jq
ZWN0QDk0OWY2OQwAMgBLDAAvADAMAC0ALgEABEphdmEHAIAMAIEAggwANgA3DACDAIQMAIUAhgwA
PQA+DABCAEYMAEIARwEAE1tMamF2YS9sYW5nL1N0cmluZzsHAIcMAIgAiQEADkhlbGxvIFdvcmxk
ISEhBwCKDACLAIwBABdqYXZhL2xhbmcvU3RyaW5nQnVpbGRlcgEADE1haW4gQXJncyA9IAwAjQCO
BwCPDACQAJEMAJAANwEABEkgPSAMADEAMQwAjQCSAQANV29ya2luZyBEaXI6IAEADGphdmEvaW8v
RmlsZQEAAS4MADIAjAwAkwA3AQAcRmFjdG9yaWFsIHVzaW5nIGxvY2FsIG1ldGhvZAEABCEgPSAB
AAlmYWN0b3JpYWwMAJQAlQEAG25ldC9uYXdhbWFuL3NjcmlwdC9GdW5jdGlvbgwAiwBLAQBBRmFj
dG9yaWFsIHVzaW5nIC4vc3NfbGlicy9mYWN0b3JpYWwuc3MgdmlhIFNjcmlwdE1hbmFnZXIuVXNl
KC4uLikBABBqYXZhL2xhbmcvT2JqZWN0BwCWDACXAJgMAEIAmQwAjQCaAQAHRE9ORSEhIQEAD21h
aW5fMTU1MjM0NDkwMwEAJ25ldC9uYXdhbWFuL3NjcmlwdC9GdW5jdGlvbiRTaW1wbGUkQm9keQEA
BEJvZHkBABRqYXZhL2lvL1NlcmlhbGl6YWJsZQEAIm5ldC9uYXdhbWFuL3NjcmlwdC9GdW5jdGlv
biRTaW1wbGUBACBuZXQvbmF3YW1hbi9zY3JpcHQvU2NyaXB0TWFuYWdlcgEACEluc3RhbmNlAQAi
TG5ldC9uYXdhbWFuL3NjcmlwdC9TY3JpcHRNYW5hZ2VyOwEAGGdldEVuZ2luZUNsYXNzTmFtZUJ5
TmFtZQEAJihMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9TdHJpbmc7AQASZ2V0RGVmYXVs
dEVuZ2luZU9mAQA1KExqYXZhL2xhbmcvU3RyaW5nOylMbmV0L25hd2FtYW4vc2NyaXB0L1Njcmlw
dEVuZ2luZTsBABBqYXZhL2xhbmcvU3lzdGVtAQADb3V0AQAVTGphdmEvaW8vUHJpbnRTdHJlYW07
AQATamF2YS9pby9QcmludFN0cmVhbQEAB3ByaW50bG4BABUoTGphdmEvbGFuZy9TdHJpbmc7KVYB
AAZhcHBlbmQBAC0oTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvU3RyaW5nQnVpbGRlcjsB
ABBqYXZhL3V0aWwvQXJyYXlzAQAIdG9TdHJpbmcBACcoW0xqYXZhL2xhbmcvT2JqZWN0OylMamF2
YS9sYW5nL1N0cmluZzsBABwoSSlMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7AQAPZ2V0QWJzb2x1
dGVQYXRoAQADVXNlAQAzKExqYXZhL2xhbmcvU3RyaW5nOylMbmV0L25hd2FtYW4vc2NyaXB0L0V4
ZWN1dGFibGU7AQARamF2YS9sYW5nL0ludGVnZXIBAAd2YWx1ZU9mAQAWKEkpTGphdmEvbGFuZy9J
bnRlZ2VyOwEAJyhbTGphdmEvbGFuZy9PYmplY3Q7KUxqYXZhL2xhbmcvT2JqZWN0OwEALShMamF2
YS9sYW5nL09iamVjdDspTGphdmEvbGFuZy9TdHJpbmdCdWlsZGVyOwAhACoAJQACACsALAADABAA
LQAuAAAAEAAvADAAAAAIADEAMQAAAAsAAQAyADMAAQA0AAAAJwACAAQAAAAPKrcAASortQACKiy1
AAOxAAAAAQA1AAAABgABAAAACgABADYANwABADQAAAAbAAEAAQAAAAMSBLAAAAABADUAAAAGAAEA
AAAKAAEAOAA5AAEANAAAACYAAgABAAAADrIABSq2AAa4AAe2AAiwAAAAAQA1AAAABgABAAAACgAB
ADoANwABADQAAAAdAAEAAQAAAAUqtAADsAAAAAEANQAAAAYAAQAAAAoAAQA7ADwAAQA0AAAAHQAB
AAEAAAAFKrQAArAAAAABADUAAAAGAAEAAAAKAAIAPQA+AAEANAAAADYABAACAAAAExsEowAHBKcA
DBsqGwRktwAJaKwAAAACADUAAAAGAAEAAAAPAD8AAAAFAAIJSAEAggBAAEEAAQA0AAAAIAADAAIA
AAAIKgErtgAKV7EAAAABADUAAAAGAAEAAAAQAIEAQgBGAAEANAAAACEABAADAAAACSoDKyy2AAsB
sAAAAAEANQAAAAYAAQAAABAAgQBCAEcAAQA0AAABiAAHAAcAAAEQLQMywAAMwAAMOgSyAA0SDrYA
D7IADbsAEFm3ABESErYAExkEuAAUtgATtgAVtgAPsgANuwAQWbcAERIWtgATsgAXtgAYtgAVtgAP
sgANuwAQWbcAERIZtgATuwAaWRIbtwActgAdtgATtgAVtgAPsgANEh62AA8DNgUVBRAKogAssgAN
uwAQWbcAERUFtgAYEh+2ABMqFQW3AAm2ABi2ABW2AA+EBQGn/9MSILgAIcAAIjoFsgANtgAjsgAN
EiS2AA8ZBcYAQwM2BhUGEAqiADmyAA27ABBZtwARFQa2ABgSH7YAExkFBL0AJVkDFQa4ACZTuQAn
AgC2ACi2ABW2AA+EBgGn/8ayAA0SKbYAD7EAAAACADUAAABKABIAAAATAAsAFQATABYAMAAXAEsA
GABvABoAdwAbAIEAHACkABsAqgAeALQAIAC6ACEAwgAiAMcAIwDRACQBAQAjAQcAJwEPACkAPwAA
ABYABP0AegcADAH6AC/9AB8HAEgB+gA8EEEAQgBJAAEANAAAAB8AAwADAAAAByorLLYACrAAAAAB
ADUAAAAGAAEAAAAKAAgASgBLAAEANAAAAB0AAQAAAAAABQOzABexAAAAAQA1AAAABgABAAAADQAC
AEwAAAACAE0ARQAAABIAAgBDACIARAQJACsAQwB9BglwcHB0ABVtYWluXzE1NTIzNDQ5MDMuY2xh
c3N0AAB1cQB+AAAAAAKfrO0ABXNyACRuZXQubmF3YW1hbi5zY3JpcHQuamF2YS5KYXZhRnVuY3Rp
b274Eu8wtf3rNQMAAHhyACJuZXQubmF3YW1hbi5zY3JpcHQuRnVuY3Rpb24kU2ltcGxlCAyTcwOU
3z4CAAJMAAdGVkluZm9zdAAoTG5ldC9uYXdhbWFuL3NjcmlwdC9Gcm96ZW5WYXJpYWJsZUluZm9z
O1sAClBhcmFtTmFtZXN0ABNbTGphdmEvbGFuZy9TdHJpbmc7eHBzcgAmbmV0Lm5hd2FtYW4uc2Ny
aXB0LkZyb3plblZhcmlhYmxlSW5mb3NDjm+xSyvbpwIAAHhwdXIAE1tMamF2YS5sYW5nLlN0cmlu
Zzut0lbn6R17RwIAAHhwAAAAAXQABSRBcmdzc3IAD21haW5fMTU1MjM0NDkwM60Sps20mVEzAgAC
TAAFJENvZGV0ABJMamF2YS9sYW5nL1N0cmluZztMAAokU2lnbmF0dXJldAAeTG5ldC9uYXdhbWFu
L3NjcmlwdC9TaWduYXR1cmU7eHBwc3IAI25ldC5uYXdhbWFuLnNjcmlwdC5TaWduYXR1cmUkU2lt
cGxlJmsgDzRSghUCAARaAAlJc1ZhckFyZ3NMAAROYW1lcQB+AAtbAApQYXJhbVR5cGVzdAASW0xq
YXZhL2xhbmcvQ2xhc3M7TAAKUmV0dXJuVHlwZXQAEUxqYXZhL2xhbmcvQ2xhc3M7eHABdAAEbWFp
bnVyABJbTGphdmEubGFuZy5DbGFzczurFteuy81amQIAAHhwAAAAAXZyABBqYXZhLmxhbmcuU3Ry
aW5noPCkOHo7s0ICAAB4cHZyAA5qYXZhLmxhbmcuVm9pZAAAAAAAAAAAAAAAeHB4dAAIICAgMTVG
Mjk=
}
##:HASHES:0x   15F29-0x   73F5B;
##:COUNTS:0x     472-0x    16AC;
*******************************************************************************/